package per;
// Generated 15 feb 2024 13:32:30 by Hibernate Tools 5.4.33.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.TemporalType;

/**
 * Cantantes generated by hbm2java
 */

@Entity
@Table(name = "cantantes",  catalog = "censo_europa")
public class Cantantes implements java.io.Serializable {

	private String pais;
	private String nombre;
	private String nombreCancion;
	private Integer numVotos;

	public Cantantes() {
	}

	public Cantantes(String pais, String nombre) {
		this.pais = pais;
		this.nombre = nombre;
	}

	public Cantantes(String pais, String nombre, String nombreCancion, Integer numVotos) {
		this.pais = pais;
		this.nombre = nombre;
		this.nombreCancion = nombreCancion;
		this.numVotos = numVotos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	@Column(name = "PAIS", unique = true, nullable = false, length = 20)
	
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}
	
	@Column(name = "NOMBRE", nullable = false, length = 20)

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "NOMBRE_CANCION", length = 100)
	
	public String getNombreCancion() {
		return this.nombreCancion;
	}

	public void setNombreCancion(String nombreCancion) {
		this.nombreCancion = nombreCancion;
	}

	@Column(name = "NUM_VOTOS")
	
	public Integer getNumVotos() {
		return this.numVotos;
	}

	public void setNumVotos(Integer numVotos) {
		this.numVotos = numVotos;
	}

}
