package per;
// Generated 15 feb 2024 13:32:30 by Hibernate Tools 5.4.33.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.TemporalType;

/**
 * Votante generated by hbm2java
 */

@Entity
@Table(name = "votante", catalog = "censo_europa")
public class Votante implements java.io.Serializable {

	private int idVotante;
	private String voto;

	public Votante() {
	}
	
	public Votante(int idVotante, String voto) {
		this.idVotante = idVotante;
		this.voto = voto;
	}

	@Id
	
	@Column(name = "ID_VOTANTE", unique = true, nullable = false)
	
	public int getIdVotante() {
		return this.idVotante;
	}

	public void setIdVotante(int idVotante) {
		this.idVotante = idVotante;
	}

	@Column(name = "VOTO", length = 20, nullable = false)
	
	public String getVoto() {
		return this.voto;
	}

	public void setVoto(String voto) {
		this.voto = voto;
	}

}
